CREATE DATABASE NEXTFLIX;
USE NEXTFLIX;

-- TABELA USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR(30) PRIMARY KEY,
    NOME VARCHAR(30),
    EMAIL VARCHAR(30) UNIQUE,
    SENHA VARCHAR(30),
    FOTO_PERFIL LONGBLOB,
    BIOGRAFIA TEXT
);

-- TABELA TITULO 
CREATE TABLE TITULO (
    ID_TITULO CHAR(30) PRIMARY KEY,
    NOME VARCHAR(30),
    GENERO VARCHAR(30),
    SINOPSE TEXT,
    DURACAO CHAR(5),
    CLASSIFICACAO_INDICATIVA CHAR(2),
    ELENCO TEXT,
    DATA_LANCAMENTO DATE
);

-- TABELA AVALIACAO
CREATE TABLE AVALIACAO (
    ID_AVALIACAO CHAR(30) PRIMARY KEY,
    ID_USUARIO CHAR(30),
    ID_TITULO CHAR(30),
    NOTA TINYINT,
    COMENTARIO TEXT,
    DATA_AVALIACAO DATE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_TITULO) REFERENCES TITULO(ID_TITULO)
);

-- TABELA COMENTARIO
CREATE TABLE COMENTARIO (
    ID_COMENTARIO CHAR(30) PRIMARY KEY,
    ID_USUARIO CHAR(30),
    ID_TITULO CHAR(30),
    TEXTO TEXT,
    DATA_COMENTARIO DATE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_TITULO) REFERENCES TITULO(ID_TITULO)
);

-- TABELA LISTA PERSONALIZADA
CREATE TABLE LISTA_PERSONALIZADA (
    ID_LISTA CHAR(30) PRIMARY KEY,
    ID_USUARIO CHAR(30),
    NOME_LISTA VARCHAR(30),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- TABELA DE RELACIONAMENTO LISTA_TITULO
CREATE TABLE LISTA_TITULO (
    ID_LISTA CHAR(30),
    ID_TITULO CHAR(30),
    PRIMARY KEY (ID_LISTA, ID_TITULO),
    FOREIGN KEY (ID_LISTA) REFERENCES LISTA_PERSONALIZADA(ID_LISTA),
    FOREIGN KEY (ID_TITULO) REFERENCES TITULO(ID_TITULO)
);

-- TABELA DE RELACIONAMENTO SEGUIR ENTRE USUARIOS
CREATE TABLE SEGUIR (
    ID_SEGUIR CHAR(30) PRIMARY KEY,
    ID_USUARIO_SEGUINDO CHAR(30),
    ID_USUARIO_SEGUIDO CHAR(30),
    FOREIGN KEY (ID_USUARIO_SEGUINDO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USUARIO_SEGUIDO) REFERENCES USUARIO(ID_USUARIO)
);

-- TABELA ADMINISTRADOR
CREATE TABLE ADMINISTRADOR (
    ID_ADMIN CHAR(30) PRIMARY KEY,
    NOME VARCHAR(30),
    EMAIL VARCHAR(30) UNIQUE,
    SENHA VARCHAR(30)
);
